# Setting the default profile as local. Can be overridden.
spring:
  profiles.active: default

  # Database Postgres
  jpa:
    hibernate.ddl-auto: none
    # Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

    # Because detection is disabled you have to set correct dialect by hand.
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

    # default schema is set to 'public'
    properties.hibernate.default_schema: public

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

    hikari:
      maximum-pool-size: 5

    flyway:
      enabled: true
      schemas: public


server:
  port: 8080

# Metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  prometheus:
    enabled: true
  endpoint:
    mappings:
      enabled: true

cassandra:
  contactpoints: localhost
  port: 9042
  keyspace: videodb
  basePackages: com.nair.kotlinreferenceapp.cassandra

kotlin-reference-app:

# Default Profile
---
spring:
  profiles: default
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
